[tool.poetry]
name = "neural-upscaler"
version = "0.1.0"
description = "Upscale images"
authors = ["Aleksi M"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
